/**
 * Error codes for Forge SDK
 */

export enum ErrorCode {
  // General errors
  UNKNOWN = 'UNKNOWN',
  INVALID_ARGUMENT = 'INVALID_ARGUMENT',

  // File system errors
  FILE_NOT_FOUND = 'FILE_NOT_FOUND',
  DIRECTORY_NOT_FOUND = 'DIRECTORY_NOT_FOUND',
  FILE_EXISTS = 'FILE_EXISTS',
  PERMISSION_DENIED = 'PERMISSION_DENIED',

  // Package errors
  PACKAGE_NOT_FOUND = 'PACKAGE_NOT_FOUND',
  INVALID_PACKAGE = 'INVALID_PACKAGE',
  VERSION_MISMATCH = 'VERSION_MISMATCH',

  // Network errors
  NETWORK_ERROR = 'NETWORK_ERROR',
  AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED',

  // Configuration errors
  CONFIG_NOT_FOUND = 'CONFIG_NOT_FOUND',
  INVALID_CONFIG = 'INVALID_CONFIG',

  // Template errors
  TEMPLATE_NOT_FOUND = 'TEMPLATE_NOT_FOUND',
  INVALID_TEMPLATE = 'INVALID_TEMPLATE',

  // Bundle errors
  BUNDLE_NOT_FOUND = 'BUNDLE_NOT_FOUND',
  INVALID_BUNDLE = 'INVALID_BUNDLE',

  // Asset errors
  ASSET_NOT_FOUND = 'ASSET_NOT_FOUND',
  MANIFEST_NOT_FOUND = 'MANIFEST_NOT_FOUND',

  // Validation errors
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INVALID_INPUT = 'INVALID_INPUT',
  INVALID_JSON = 'INVALID_JSON',

  // Extraction errors
  EXTRACTION_ERROR = 'EXTRACTION_ERROR',
}
